name: Maintain Stale branches
description: This action serves to maintain stale branches

inputs:
  token:
    description: 'GitHub token used to create an authenticated client'
    required: true
  repository:
    description: 'Slug of the repo on the format owner/repo'
    required: true
  days_to_stale:
    description: 'Quantity of days branch be considered stale'
    required: true

runs: 
  using: 'docker'
  image: 'Dockerfile'