name: Maintain Stale branches
description: This action serves to maintain stale branches

input:
  token:
    description: 'The GitHub token used to create an authenticated client'
    required: true
  repository:
    description: 'owner/repo'
    required: true
  developer_team_slug:
    description: 'developer team slug'
    required: true
  admin_team_slug:
    description: 'admin team slug'
    required: true

runs: 
  using: 'docker'
  image: 'Dockerfile'