name: Maintain Stale branches
description: This action serves to maintain stale branches

input:
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    default: ${{ github.token }}
    required: false
  repo:
    description: 'owner/repo'
    required: true
  developer_team_slug:
    description: 'developer team slug'
    required: true
  admin_team_slug:
    description: 'admin team slug'
    required: true

runs: 
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.developer_team_slug }}
    - ${{ inputs.admin_team_slug }}