name: Test 

on: 
  workflow_dispatch:
    inputs:
      days_to_stale:
        description: 'Quantity of days since last modification to branch be considered stale'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test maintain-remove-stale-branches
        uses: LucasAzevedo23/maintain-remove-stale-branches@a76f2a8aa24afa303de2f92b78bbbb52997be14d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          days_to_stale: ${{ github.event.inputs.days_to_stale }}