name: Test 

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test maintain-remove-stale-branches
        uses: LucasAzevedo23/maintain-remove-stale-branches@02bf7f387701a2074f1c48f9ddd8b82a438f80ed
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          developer_team_slug: developer_team_slug
          admin_team_slug: admin_team_slug