name: Test 

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test maintain-remove-stale-branches
        uses: LucasAzevedo23/maintain-remove-stale-branches@4abef2ae9f466f7fe0dd7630fdd121318653434d
        with:
          token: test_token
          repository: ${{ github.repository }}
          developer_team_slug: developer_team_slug
          admin_team_slug: admin_team_slug